### PR TITLE
Up Maven plugins

### PR DESCRIPTION
**Pull request by dmitry-timofeev**
## Overview
Up Maven plugins

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Changelog is updated if needed (in case of notable or breaking changes)
- [ ] The continuous integration build passes

### CODE REVIEW

**Comment by dmitry-timofeev** [comment]
> Any particular reasons to change versions ?

Why does software updates?

**Comment by dmitry-timofeev** [comment]
No particular reasons — just staying on the most recent versions.

**Comment by DENMROOT** [comment]
:) That's a good one. Usually I update dependencies after some required
changes in them, not just every time they had updated.

вт, 25 сент. 2018 г. в 15:58, Dmitry Timofeev <notifications@github.com>:

**Comment by dmitry-timofeev** [comment]
But the software usually improves — bugs and vulnerabilities get fixed, compatibility improves, new features are delivered.

**Pull request merged**
