### PR TITLE
Enable a test verifying independence of collection groups

### PR DESCRIPTION
**Pull request by dmitry-timofeev**
## Overview

It seems the collection groups became independent in MerkleDB,
and modifications of a collection in one group cannot affect
collections in other groups, even if first group id is a sub-prefix
of the other group id.

---

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Changelog is updated if needed (in case of notable or breaking changes)
- [x] The continuous integration build passes

### CODE REVIEW

**Comment by dmitry-timofeev** [comment]
@aleksuss are they really independent now? Is such (or similar) situation impossible in MerkleDB?

**Comment by MakarovS** [comment]
CI fails though :(

**Comment by aleksuss** [comment]
@dmitry-timofeev Yes. They are really independent. Each index instance has its own identifier which is a part of the key.

**Comment by dmitry-timofeev** [comment]
> CI fails though :(

Weird, Exonum no longer compiles (this test passed, but I ran it through IDE, so no native lib compilation happened). 

However, there is a new release of Rust, so we must absolutely not be surprised that something broke (@vitvakatu , @skletsun ): https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1370-2019-08-15

**Pull request merged**
