### PR TITLE
Lombok prototype [ECR-2754]

### PR DESCRIPTION
**Pull request by MakarovS**
## Overview
Prototype to compare Lombok with AutoValue.

---
See: https://jira.bf.local/browse/ECR-2754

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Change is covered by automated [tests](https://github.com/exonum/exonum-java-binding/blob/master/CONTRIBUTING.md#tests)
- [x] The [coding guidelines](https://github.com/exonum/exonum-java-binding/blob/master/CONTRIBUTING.md#the-code-style) are followed
- [x] Public API has Javadoc
- [x] Method preconditions are checked and documented in the Javadoc of the method
- [x] Changelog is updated if needed (in case of notable or breaking changes)
- [x] The continuous integration build passes

### CODE REVIEW

**Comment by bullet-tooth** [comment]
Also lombok has another helpful features such us https://projectlombok.org/features/SneakyThrows
which can be used, for example, at `com.exonum.binding.storage.indices.BaseIndexGroupTestable#close`

**Comment by bullet-tooth** [comment]
Checked the javadoc question 1 ⬆️ 
You can write the javadoc on the field. And then this test is copied to the getters, setters and builder's fields as is without  any modifications

**Comment by dmitry-timofeev** [comment]
Thanks, that makes sense! Although it violates the code style, it will work in most cases, but if one needs to specify preconditions, exceptions, etc., then the second question arises.

**Comment by MakarovS** [comment]
@dmitry-timofeev @bullet-tooth yes, you can have separate docs for getters and setters:
`
NEW in lombok v1.12.0: javadoc on the field will now be copied to generated getters and setters. Normally, all text is copied, and @return is moved to the getter, whilst @param lines are moved to the setter. Moved means: Deleted from the field's javadoc. It is also possible to define unique text for each
getter/setter. To do that, you create a 'section' named GETTER and/or SETTER. A section is a line in your javadoc containing 2 or more dashes, then the text 'GETTER' or 'SETTER', followed by 2 or more dashes, and nothing else on the line. If you use sections, @return and @param stripping for that section is no longer done (move the @return or @param line into the section).
`

Like this:
```
  /**
   * Name of the person.
   * -- SETTER --
   * Changes the name of this person.
   * 
   * @param name The new value.
   */
```

And literally just 1.5 months ago they fixed builder javadocs - now they are copied the same way as they are copied to setter, here's the PR https://github.com/rzwitserloot/lombok/pull/2008

If there are no more questions, we can close this PR.

**Comment by dmitry-timofeev** [comment]
That's good, thanks!

**Pull request closed without merging**
