### PR TITLE
Remove .size() & .is_empty() methods [ECR-3443]

### PR DESCRIPTION
**Pull request by skletsun**
## Overview
Removed recently added methods for indices. Also pointing the branch to new release of exonum v0.12.

---
See: https://jira.bf.local/browse/ECR-3443

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Change is covered by automated [tests](https://github.com/exonum/exonum-java-binding/blob/master/CONTRIBUTING.md#tests)
- [x] The [coding guidelines](https://github.com/exonum/exonum-java-binding/blob/master/CONTRIBUTING.md#the-code-style) are followed
- [x] Public API has Javadoc
- [x] Method preconditions are checked and documented in the Javadoc of the method
- [x] Changelog is updated if needed (in case of notable or breaking changes)
- [x] The continuous integration build passes

### CODE REVIEW

**Comment by vitvakatu** [comment]
Btw, our scripts are broken in 0.12, as it now has the different parameters for `generate-config` https://github.com/exonum/exonum-java-binding/blob/f43e941035b5b6b10dd39db0439bc75f3d490c19/exonum-java-binding/core/rust/exonum-java/start_cryptocurrency_node.sh#L63
https://github.com/exonum/exonum/blob/ce1caf9c722626b373158b24f45ba16f6546a10a/exonum/src/helpers/fabric/details.rs#L480

**Comment by vitvakatu** [comment]
So I'd fix our scripts and manuals in this or following PR

**Comment by skletsun** [comment]
> So I'd fix our scripts and manuals in this or following PR
Thanks. If that's all we need to do in order to point 0.12 then it probably makes sense to do it within this PR. Otherwise, I'll put these changes into separate PR.

**Comment by vitvakatu** [comment]
I'm not aware of any other significant changes, so as the tests are green - I assume we're okay with our code. Requesting review from @dip56 to make sure our system tests also passed on this PR.

**Comment by skletsun** [comment]
> If anything else is required to update to 0.12, please extract the whole thing in a separate PR.

Well, looks like working with 0.12 requires further improvements -> going to extract it into a separate PR.

**Comment by dmitry-timofeev** [comment]
OK, keep the two commits, and push the other one in a new branch, please.

**Pull request merged**
