### PR TITLE
Add project version to generated apidocs path

### PR DESCRIPTION
**Pull request by vitvakatu**
## Overview

Now javadocs placed inside apidocs/<version> directory:
```
[INFO] Javadoc archive created in /Users/ilyabogdanov/projects/exonum-java-binding/exonum-java-binding/target/site//java-binding-apidocs.zip
⇒  unzip -l java-binding-apidocs.zip 
Archive:  java-binding-apidocs.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  02-13-2020 16:53   apidocs/
        0  02-13-2020 16:53   apidocs/0.10.0-SNAPSHOT/
        0  02-13-2020 16:53   apidocs/0.10.0-SNAPSHOT/apidocs/
    91492  02-13-2020 16:53   apidocs/0.10.0-SNAPSHOT/apidocs/constant-values.html
   121254  02-13-2020 16:53   apidocs/0.10.0-SNAPSHOT/apidocs/overview-tree.html
     3003  02-13-2020 16:53   apidocs/0.10.0-SNAPSHOT/apidocs/index.html
```

---
See: https://jira.bf.local/browse/ECR-XYZ

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Change is covered by automated [tests](https://github.com/exonum/exonum-java-binding/blob/master/CONTRIBUTING.md#tests)
- [ ] The [coding guidelines](https://github.com/exonum/exonum-java-binding/blob/master/CONTRIBUTING.md#the-code-style) are followed
- [ ] Public API has Javadoc
- [ ] Method preconditions are checked and documented in the Javadoc of the method
- [ ] Changelog is updated if needed (in case of notable or breaking changes)
- [ ] The continuous integration build passes

### CODE REVIEW

**Comment by dmitry-timofeev** [comment]
The maven-javadoc-plugin configuration is ... weird. They have two seemingly identical properties:
`outputDirectory` and `reportOutputDirectory` with the first said to have an alias `destDir`, which actually appears to be a separate property (because setting outputDirectory and destDir leads to different results). 

Such config:

```
Index: exonum-java-binding/pom.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- exonum-java-binding/pom.xml	(revision 5f9c189efc0920e2b71496174d70920e83873ae9)
+++ exonum-java-binding/pom.xml	(date 1581607652201)
@@ -419,6 +419,9 @@
             <doclint>none</doclint>
             <detectOfflineLinks>false</detectOfflineLinks>
             <additionalJOption>${maven.javadoc.joption}</additionalJOption>
+            <!-- Use a custom output directory to simplify the deploy procedure to the web-site -->
+            <reportOutputDirectory>${project.reporting.outputDirectory}/apidocs</reportOutputDirectory>
+            <destDir>${project.version}</destDir>
           </configuration>
           <executions>
             <execution>

```

Allows to produce Javadocs in `target/site/apidocs/<version>` (with no extra apidocs). However, @atrykush said he did that separately through a configuration parameter.

**Comment by vitvakatu** [comment]
@dmitry-timofeev so should I use your solution or leave it as it is?

**Comment by dmitry-timofeev** [comment]
> @dmitry-timofeev so should I use your solution or leave it as it is?

> However, @atrykush said he did that separately through a configuration parameter.

I am not sure it is needed any longer. @atrykush, is it needed? If not, I'd keep it as is as the configuration, as I've mentioned, is complicated.

**Comment by vitvakatu** [comment]
Closing as not needed.

**Pull request closed without merging**
