### PR TITLE
Update README.md and setup.py for Python modules [ECR-3992]

### PR DESCRIPTION
**Pull request by vitvakatu**
## Overview

Python modules have been published with the following changes.

---
See: https://jira.bf.local/browse/ECR-3992

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Change is covered by automated [tests](https://github.com/exonum/exonum-java-binding/blob/master/CONTRIBUTING.md#tests)
- [ ] The [coding guidelines](https://github.com/exonum/exonum-java-binding/blob/master/CONTRIBUTING.md#the-code-style) are followed
- [ ] Public API has Javadoc
- [ ] Method preconditions are checked and documented in the Javadoc of the method
- [ ] Changelog is updated if needed (in case of notable or breaking changes)
- [ ] The continuous integration build passes

### CODE REVIEW

**Comment by dmitry-timofeev** [comment]
@popzxc Would you please review the extension updates?

**Comment by dmitry-timofeev** [comment]
Why does it use a different version from the rest of the project?

**Comment by vitvakatu** [comment]
> Why does it use a different version from the rest of the project (on Pypi)?

A small oversight by me. PyPI doesn't like certain version formats, like `0.9.0-rc1`, or `0.9.0-rc1.2` which are totally possible in semantic versioning. So I changed it to `dev1` for testing purpose and forgot to change it back.

I published another release with version `0.9.0rc1`, it is now available at PyPI.

**Comment by dmitry-timofeev** [comment]
> PyPI doesn't like certain version formats

Does it forbid some version strings, allowed by semver?

**Comment by popzxc** [comment]
>Does it forbid some version strings, allowed by semver?

Even if it doesn't, it's not consistent with convention. Even the `cpython` project itself uses the following format:
image

**Pull request merged**
