### PR TITLE
Skip Java integration tests on Linux only [ECR-1742]:

### PR DESCRIPTION
**Pull request by dmitry-timofeev**
## Overview

Disable Java tests requiring the native library on Linux until the loading bug is fixed (ECR-942).

---
See: https://jira.bf.local/browse/ECR-1742

### Definition of Done

- [x] There are no TODOs left in the code
- [x] Change is covered by automated tests
- [x] The [coding guidelines](https://google.github.io/styleguide/javaguide.html) are followed
- [x] The [continuous integration build](https://www.travis-ci.org/exonum/exonum-java-binding) passes

### CODE REVIEW

**Comment by dmitry-timofeev** [comment]
Our Mac users, would you test it locally please (@alexander-irbis, @MakarovS )? 

I think it might require setting `LD_LIBRARY_PATH` environment variable to contain the path to the Rust standard library.

**Comment by dmitry-timofeev** [comment]
@bullet-tooth, @MakarovS , Travis running on Linux still skips the ITs, would you please test on a Mac locally that tests pass after various updates?

**Comment by dmitry-timofeev** [comment]
Merged, will test in master :trollface:

**Comment by MakarovS** [comment]
@dmitry-timofeev I just tested this branch - it worked

**Pull request merged**
