### PR TITLE
Fix build after #844

### PR DESCRIPTION
**Pull request by vitvakatu**
## Overview

---
See: https://jira.bf.local/browse/ECR-XYZ

### Definition of Done

- [ ] There are no TODOs left in the code
- [ ] Change is covered by automated [tests](https://github.com/exonum/exonum-java-binding/blob/master/CONTRIBUTING.md#tests)
- [ ] The [coding guidelines](https://github.com/exonum/exonum-java-binding/blob/master/CONTRIBUTING.md#the-code-style) are followed
- [ ] Public API has Javadoc
- [ ] Method preconditions are checked and documented in the Javadoc of the method
- [ ] Changelog is updated if needed (in case of notable or breaking changes)
- [ ] The continuous integration build passes

### CODE REVIEW

**Comment by dmitry-timofeev** [comment]
How did it fail if #844 passed after merge :confused:

**Comment by vitvakatu** [comment]
Yep, that's weird. This module is activate only without resource manager, but we indeed have this testing step (visible in logs)

**Comment by dmitry-timofeev** [comment]
But the parent … wasn't broken: https://travis-ci.com/exonum/exonum-java-binding/builds/109424184

**Comment by dmitry-timofeev** [comment]
What is the issue exactly? Do we have an issue with our build system if some problems are not detected?

**Comment by vitvakatu** [comment]
Investigating, please do not merge. Looks like we're not testing no-resource-manager with `run_all_tests`

**Comment by dmitry-timofeev** [comment]
Might it have something to do with https://github.com/exonum/exonum-java-binding/issues/691 (it only changes Cargo.toml of _app_, not _java-bindings_ library)?

**Comment by vitvakatu** [comment]
@dmitry-timofeev good catch, actually. It took some time, but I found out that this change is indeed the source of the problem.

**Pull request merged**
